require 'rspec/core/rake_task'

desc "Start the API Server through rackup."
task :serve do
  sh 'rerun --notify notify-send -- rackup --host 0.0.0.0 --port 9292'
end

RSpec::Core::RakeTask.new(:spec)

task default: :serve
